#!/bin/sh


ln -sf "$PWD/.vimrc" "$HOME/.vimrc"
ln -sf "$PWD/.tmux.conf" "$HOME/.tmux.conf"
ln -sf "$PWD/.bash_profile" "$HOME/.bash_profile"
ln -sf "$PWD/.vim" "$HOME/.vim"
ln -sf "$PWD/bin" "$HOME/bin"
